name: "dev-check-changed-packages"
on:
  push:
    branches: [dev]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      # Defining a job output for used by the next jobs:
      app1_changed: ${{ steps.changedAction1.outputs.changed }}
      app2_changed: ${{ steps.changedAction2.outputs.changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary so we have commit history to compare to

      - name: app1 changed in last commit?
        id: changedAction1
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: app1
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead)

      - name: app2 changed in last commit?
        id: changedAction2
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: app2
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead)

  call_dev-app1_workflow:
    needs: [check]
    if: needs.check.outputs.app1_changed == 'true' # Check output if it changed or not (returns a boolean)
    uses: ./.github/workflows/dev-app1.yml

  call_dev-app2_workflow:
    needs: [check]
    if: needs.check.outputs.app2_changed == 'true' # Check output if it changed or not (returns a boolean)
    uses: ./.github/workflows/dev-app2.yml
